version: "3.9"
services:
  db:
    image: postgres:15.0-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5460:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mdn_development

volumes:
  db-data:
