default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mdn_development

test:
  <<: *default
  database: mdn_test

#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>

production:
  <<: *default
  database: mdn_production
  username: mdn
  password: <%= ENV["MDN_DATABASE_PASSWORD"] %>
